In [1]:
import numpy as np


In [2]:
##Creating an activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
trainings_inputs=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
print(trainings_inputs)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [4]:
trainings_outputs=np.array([[0],[1],[1],[0]])
print(trainings_outputs)

[[0]
 [1]
 [1]
 [0]]


In [5]:
##initial weights 
np.random.seed(1)  # to set constant random trail 
weight=2*np.random.random((3,1))-1
print(weight)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [6]:
def sigmoid_derivative(x):
    return x*(1-x)

In [11]:
for i in range(1000):
    input_layer=trainings_inputs
    #print(np.dot(input_layer,weight))
    outputs=sigmoid(np.dot(input_layer,weight))
    error=trainings_outputs-outputs
    adjustments=error*sigmoid_derivative(outputs)
    weight+=np.dot(input_layer.T,adjustments)
    print(weight)
    #.T for transpose

[[ 7.26390912]
 [-0.21614179]
 [-3.41757429]]
[[ 7.26498704]
 [-0.2161374 ]
 [-3.41811787]]
[[ 7.26606383]
 [-0.21613302]
 [-3.41866088]]
[[ 7.26713952]
 [-0.21612864]
 [-3.41920334]]
[[ 7.26821409]
 [-0.21612427]
 [-3.41974523]]
[[ 7.26928755]
 [-0.2161199 ]
 [-3.42028656]]
[[ 7.27035991]
 [-0.21611553]
 [-3.42082733]]
[[ 7.27143116]
 [-0.21611116]
 [-3.42136754]]
[[ 7.27250131]
 [-0.21610681]
 [-3.4219072 ]]
[[ 7.27357036]
 [-0.21610245]
 [-3.4224463 ]]
[[ 7.27463832]
 [-0.2160981 ]
 [-3.42298485]]
[[ 7.27570517]
 [-0.21609375]
 [-3.42352285]]
[[ 7.27677094]
 [-0.21608941]
 [-3.42406029]]
[[ 7.27783561]
 [-0.21608507]
 [-3.42459718]]
[[ 7.2788992 ]
 [-0.21608073]
 [-3.42513353]]
[[ 7.2799617 ]
 [-0.2160764 ]
 [-3.42566932]]
[[ 7.28102311]
 [-0.21607207]
 [-3.42620457]]
[[ 7.28208345]
 [-0.21606774]
 [-3.42673927]]
[[ 7.2831427 ]
 [-0.21606342]
 [-3.42727342]]
[[ 7.28420087]
 [-0.2160591 ]
 [-3.42780704]]
[[ 7.28525797]
 [-0.21605479]
 [-3.4283401 ]]
[[ 7.286314  ]
 [-0.21605048]
 [-3

 [-3.56943095]]
[[ 7.5659114 ]
 [-0.21489797]
 [-3.56983743]]
[[ 7.5667172 ]
 [-0.21489464]
 [-3.5702436 ]]
[[ 7.56752237]
 [-0.21489131]
 [-3.57064945]]
[[ 7.56832691]
 [-0.21488799]
 [-3.57105498]]
[[ 7.56913083]
 [-0.21488466]
 [-3.5714602 ]]
[[ 7.56993412]
 [-0.21488134]
 [-3.5718651 ]]
[[ 7.57073679]
 [-0.21487803]
 [-3.57226969]]
[[ 7.57153884]
 [-0.21487471]
 [-3.57267396]]
[[ 7.57234027]
 [-0.2148714 ]
 [-3.57307792]]
[[ 7.57314107]
 [-0.21486809]
 [-3.57348157]]
[[ 7.57394126]
 [-0.21486478]
 [-3.57388491]]
[[ 7.57474083]
 [-0.21486148]
 [-3.57428793]]
[[ 7.57553978]
 [-0.21485818]
 [-3.57469064]]
[[ 7.57633812]
 [-0.21485488]
 [-3.57509304]]
[[ 7.57713584]
 [-0.21485158]
 [-3.57549513]]
[[ 7.57793294]
 [-0.21484829]
 [-3.5758969 ]]
[[ 7.57872943]
 [-0.214845  ]
 [-3.57629837]]
[[ 7.57952531]
 [-0.21484171]
 [-3.57669953]]
[[ 7.58032058]
 [-0.21483842]
 [-3.57710038]]
[[ 7.58111523]
 [-0.21483514]
 [-3.57750092]]
[[ 7.58190928]
 [-0.21483186]
 [-3.57790115]]
[[ 7.58270272]
 [-

[[ 7.77731582]
 [-0.21402932]
 [-3.6763765 ]]
[[ 7.77797253]
 [-0.21402664]
 [-3.67670739]]
[[ 7.77862883]
 [-0.21402397]
 [-3.67703807]]
[[ 7.7792847 ]
 [-0.2140213 ]
 [-3.67736854]]
[[ 7.77994016]
 [-0.21401863]
 [-3.67769879]]
[[ 7.78059521]
 [-0.21401596]
 [-3.67802884]]
[[ 7.78124983]
 [-0.2140133 ]
 [-3.67835867]]
[[ 7.78190405]
 [-0.21401063]
 [-3.6786883 ]]
[[ 7.78255784]
 [-0.21400797]
 [-3.67901772]]
[[ 7.78321123]
 [-0.21400531]
 [-3.67934692]]
[[ 7.7838642 ]
 [-0.21400266]
 [-3.67967592]]
[[ 7.78451675]
 [-0.214     ]
 [-3.68000471]]
[[ 7.7851689 ]
 [-0.21399735]
 [-3.68033329]]
[[ 7.78582063]
 [-0.21399469]
 [-3.68066167]]
[[ 7.78647195]
 [-0.21399204]
 [-3.68098983]]
[[ 7.78712285]
 [-0.2139894 ]
 [-3.68131779]]
[[ 7.78777335]
 [-0.21398675]
 [-3.68164554]]
[[ 7.78842344]
 [-0.2139841 ]
 [-3.68197309]]
[[ 7.78907312]
 [-0.21398146]
 [-3.68230042]]
[[ 7.78972239]
 [-0.21397882]
 [-3.68262755]]
[[ 7.79037125]
 [-0.21397618]
 [-3.68295448]]
[[ 7.7910197 ]
 [-0.21397354]
 [-3

 [-3.76555251]]
[[ 7.95488753]
 [-0.21331426]
 [-3.76583106]]
[[ 7.95544026]
 [-0.21331206]
 [-3.76610946]]
[[ 7.9559927 ]
 [-0.21330986]
 [-3.76638771]]
[[ 7.95654484]
 [-0.21330767]
 [-3.7666658 ]]
[[ 7.95709669]
 [-0.21330548]
 [-3.76694375]]
[[ 7.95764824]
 [-0.21330328]
 [-3.76722155]]
[[ 7.95819949]
 [-0.21330109]
 [-3.7674992 ]]
[[ 7.95875045]
 [-0.21329891]
 [-3.7677767 ]]
[[ 7.95930111]
 [-0.21329672]
 [-3.76805406]]
[[ 7.95985148]
 [-0.21329453]
 [-3.76833126]]
[[ 7.96040156]
 [-0.21329235]
 [-3.76860831]]
[[ 7.96095134]
 [-0.21329017]
 [-3.76888522]]
[[ 7.96150082]
 [-0.21328798]
 [-3.76916198]]
[[ 7.96205002]
 [-0.2132858 ]
 [-3.76943859]]
[[ 7.96259892]
 [-0.21328362]
 [-3.76971505]]
[[ 7.96314753]
 [-0.21328145]
 [-3.76999137]]
[[ 7.96369584]
 [-0.21327927]
 [-3.77026753]]
[[ 7.96424386]
 [-0.21327709]
 [-3.77054355]]
[[ 7.9647916 ]
 [-0.21327492]
 [-3.77081942]]
[[ 7.96533903]
 [-0.21327275]
 [-3.77109515]]
[[ 7.96588618]
 [-0.21327058]
 [-3.77137073]]
[[ 7.96643304]
 [-

In [12]:
#working for above code
#print(sigmoid(-3.79003922))
#then error is deduced 
print(sigmoid_derivative(outputs))

[[0.02161825]
 [0.01767528]
 [0.01438176]
 [0.01761788]]


In [13]:
weight

array([[ 8.0024254 ],
       [-0.21312605],
       [-3.78977343]])

In [10]:
outputs.round()

array([[0.],
       [1.],
       [1.],
       [0.]])